### ISSUE TITLE
Anki 2.1.20beta6 error

### ISSUE THREAD

**Issue by khonkhortisan** [scottgigante/korean-support#3]
When loading 'Korean Support':
Traceback (most recent call last):
  File "aqt\addons.py", line 201, in loadAddons
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1336389630\__init__.py", line 35, in <module>
    for dir in mgr.managedAddons():
AttributeError: 'AddonManager' object has no attribute 'managedAddons'

**Comment by scottgigante** [comment]
Looks like `managedAddons` was removed from `AddonManager` in the last month. Thanks for reporting!
